### ISSUE TITLE
UI audio is low on high volume

### ISSUE THREAD

**Issue by ghost** [Neternels/android_kernel_xiaomi_mojito#1]
Noticed it when I'm on stock kernel / on other kernels like Anush's WCSF, neternels tend to lower UI sounds like keyboard, touch, etc.
Can the volume gain be tweaked ?

**Comment by cyberknight777** [comment]
@pc00per you mean audio isn't loud enough only on my kernel?

**Comment by ghost** [comment]
Yep. Looks like that's the case.
Once ask your tg community to test it by changing to an another kernel, such as anush's one.
The main issue is the UI audio suppressing, such as lock/unlock/keypresses/keyboard.

**Comment by cyberknight777** [comment]
@pc00per Unless you can provide a spreadsheet with the relevant stats comparing audio loudness between my kernel and other kernels, I will not give much incentive to this issue.

If loudness was an issue, my users would've told me long ago.

**Comment by ghost** [comment]
Welp. I don't have relavant tools to benchmark the loudness. But it's clearly distinguishable right on.

**Comment by cyberknight777** [comment]
@pc00per I don't feel it on my mojito, I've used miui for a week and switched to aosp afterwards and I didn't see any differences anyhow.

**Comment by ghost** [comment]
I felt the same, until I've tried wcsf. His tweaks seem to improve the UI audio even better. Might consider this as an enhancement rather an issue would be better.

**Comment by cyberknight777** [comment]
@pc00per what rom you on?

**Comment by ghost** [comment]
GSI actually. But the behavior pans out the same on ROMs too.
I was on anush's crD & zid's PE a month back. Also tested on andy's lineage as well as nazim's spark & Arrow.
Currently on nazim's crD.

**Comment by cyberknight777** [comment]
@pc00per You're saying it's louder than stock?

**Comment by ghost** [comment]
You mean meme's perf on stock? Lemme test it again & make sure if it's correct...

**Comment by cyberknight777** [comment]
@pc00per Also what trees are used to build the crdroid you're running on rn

**Comment by ghost** [comment]
> @pc00per Also what trees are used to build the crdroid you're running on rn

Welp. GSIs don't have trees. Devs operate on [patches](https://github.com/naz664/crDroid_gsi).
The actual device adaptation happens with [vendor overlays](https://github.com/phhusson/vendor_hardware_overlay/tree/pie/Xiaomi/RedmiNote10) that enable certain fixes & improvements on top of system UI.
But I don't think overlay's the factor caz the behavior changes on kernels.

**Comment by cyberknight777** [comment]
@pc00per Are you very sure it happens only on my kernel and not other kernels

**Comment by ghost** [comment]
> @pc00per Are you very sure it happens only on my kernel and not other kernels

On yours, the decibels are a tad lower when compared to wcsf, which is absolute. 
Not sure about stock, will let you know in couple minutes how it behaves.

**Comment by cyberknight777** [comment]
@pc00per I'll send b15 soon, check on it and lmk.

**Comment by cyberknight777** [comment]
@pc00per On second thoughts, contact me  via email and I'll send you the build to test

**Comment by ghost** [comment]
You should receive my mail btw. Primary mails aren't to be disclosed anyways.

**Comment by cyberknight777** [comment]
@pc00per yeah I saw. I'll send a build once I'm done with it.

**Comment by ghost** [comment]
Just tested the stock perf, & ui decibels seem to be louder asusual.

**Comment by cyberknight777** [comment]
@pc00per Alright thanks for notifying.

**Comment by ghost** [comment]
This might be weird that I noticed but, wcsf had some kind of audio boosts. Actually much louder & crisper even compared to stock.
Just wondering that it's anush's kernel that's louder, not the other way around...
Looks like this is an enhancement request. You could try his audio kernel patches if nothing works at the end...

**Comment by cyberknight777** [comment]
@pc00per There's no relevant patches as I've seen, if you can provide a spreadsheet sure I can have a deeper look into it. Till then I'm not going to have a deeper look into it

**Comment by cyberknight777** [comment]
@pc00per have you tested the latest build

**Comment by ghost** [comment]
Yup. Unfortunately no changes observed. I think it's better leave this btw not worth dabbling into it. Current UI sounds are atleast audible anyways
